namespace Utils
{
    public static class Strings
    {
        public static string FOREX = "FOREX";
        public static string SERVICES_ACTIVESMS = "SERVICES_ACTIVESMS";

        public static string SERVICES_PAGINATION = "SERVICES_PAGINATION";
        public static string CHATID_CURRENT_PAGE = "CHATID_CURRENT_PAGE";
        public static string CHATID_CURRENT_SERVICES_PAGINATION = "CHATID_CURRENT_SERVICES_PAGINATION";

        public static string USER_CART = "USER_CART";
        public static string PREFIX_RENT_SMS_SERVICE = "rentsms:";
        public static string PRE_RENT_DATA_SMS_SERVICE = "PRE_RENT_DATA_SMS_SERVICE";
        public static string CURRENT_USER_RENT_SERVICE = "CURRENT_USER_RENT_SERVICE";
        public static string CURRENT_COUTRY_SERVICE = "CURRENT_COUTRY_SERVICE";

        public static string CURRENT_SERVER = "CURRENT_SERVER";

        public static List<Country> Countries = new List<Country>
        {
            new Country {CountryNumber= "73", Title= "Brazil"},
            new Country {CountryNumber= "12", Title= "United States"},
            new Country {CountryNumber= "1", Title= "Ukraine"},
            new Country {CountryNumber= "2", Title= "Kazakhstan"},
            new Country {CountryNumber= "3", Title= "China"},
            new Country {CountryNumber= "4", Title= "Philippines"},
            new Country {CountryNumber= "5", Title= "Myanmar"},
            new Country {CountryNumber= "6", Title= "Indonesia"},
            new Country {CountryNumber= "7", Title= "Malaysia"},
            new Country {CountryNumber= "8", Title= "Kenya"},
            new Country {CountryNumber= "9", Title= "Tanzania"},
            new Country {CountryNumber= "10", Title= "Vietnam"},
            new Country {CountryNumber= "11", Title= "Kyrgyzstan"},
            new Country {CountryNumber= "13", Title= "Israel"},
            new Country {CountryNumber= "14", Title= "Hong Kong"},
            new Country {CountryNumber= "15", Title= "Poland"},
            new Country {CountryNumber= "16", Title= "England"},
            new Country {CountryNumber= "17", Title= "Madagascar"},
            new Country {CountryNumber= "18", Title= "DCongo"},
            new Country {CountryNumber= "19", Title= "Nigeria"},
            new Country {CountryNumber= "20", Title= "Macao"},
            new Country {CountryNumber= "21", Title= "Egypt"},
            new Country {CountryNumber= "22", Title= "India"},
            new Country {CountryNumber= "23", Title= "Ireland"},
            new Country {CountryNumber= "24", Title= "Cambodia"},
            new Country {CountryNumber= "25", Title= "Laos"},
            new Country {CountryNumber= "26", Title= "Haiti"},
            new Country {CountryNumber= "27", Title= "Ivory"},
            new Country {CountryNumber= "28", Title= "Gambia"},
            new Country {CountryNumber= "29", Title= "Serbia"},
            new Country {CountryNumber= "30", Title= "Yemen"},
            new Country {CountryNumber= "31", Title= "Southafrica"},
            new Country {CountryNumber= "32", Title= "Romania"},
            new Country {CountryNumber= "33", Title= "Colombia"},
            new Country {CountryNumber= "34", Title= "Estonia"},
            new Country {CountryNumber= "35", Title= "Azerbaijan"},
            new Country {CountryNumber= "36", Title= "Canada"},
            new Country {CountryNumber= "37", Title= "Morocco"},
            new Country {CountryNumber= "38", Title= "Ghana"},
            new Country {CountryNumber= "39", Title= "Argentina"},
            new Country {CountryNumber= "40", Title= "Uzbekistan"},
            new Country {CountryNumber= "41", Title= "Cameroon"},
            new Country {CountryNumber= "42", Title= "Chad"},
            new Country {CountryNumber= "43", Title= "Germany"},
            new Country {CountryNumber= "44", Title= "Lithuania"},
            new Country {CountryNumber= "45", Title= "Croatia"},
            new Country {CountryNumber= "46", Title= "Sweden"},
            new Country {CountryNumber= "47", Title= "Iraq"},
            new Country {CountryNumber= "48", Title= "Netherlands"},
            new Country {CountryNumber= "49", Title= "Latvia"},
            new Country {CountryNumber= "50", Title= "Austria"},
            new Country {CountryNumber= "51", Title= "Belarus"},
            new Country {CountryNumber= "52", Title= "Thailand"},
            new Country {CountryNumber= "53", Title= "Saudiarabia"},
            new Country {CountryNumber= "54", Title= "Mexico"},
            new Country {CountryNumber= "55", Title= "Taiwan"},
            new Country {CountryNumber= "56", Title= "Spain"},
            new Country {CountryNumber= "57", Title= "Iran"},
            new Country {CountryNumber= "58", Title= "Algeria"},
            new Country {CountryNumber= "59", Title= "Slovenia"},
            new Country {CountryNumber= "60", Title= "Bangladesh"},
            new Country {CountryNumber= "61", Title= "Senegal"},
            new Country {CountryNumber= "62", Title= "Turkey"},
            new Country {CountryNumber= "63", Title= "Czech"},
            new Country {CountryNumber= "64", Title= "Srilanka"},
            new Country {CountryNumber= "65", Title= "Peru"},
            new Country {CountryNumber= "66", Title= "Pakistan"},
            new Country {CountryNumber= "67", Title= "New Zealand"},
            new Country {CountryNumber= "68", Title= "Guinea"},
            new Country {CountryNumber= "69", Title= "Mali"},
            new Country {CountryNumber= "70", Title= "Venezuela"},
            new Country {CountryNumber= "71", Title= "Ethiopia"},
            new Country {CountryNumber= "72", Title= "Mongolia"},
            new Country {CountryNumber= "74", Title= "Afghanistan"},
            new Country {CountryNumber= "75", Title= "Uganda"},
            new Country {CountryNumber= "76", Title= "Angola"},
            new Country {CountryNumber= "77", Title= "Cyprus"},
            new Country {CountryNumber= "78", Title= "France"},
            new Country {CountryNumber= "79", Title= "Papua"},
            new Country {CountryNumber= "80", Title= "Mozambique"},
            new Country {CountryNumber= "81", Title= "Nepal"},
            new Country {CountryNumber= "82", Title= "Belgium"},
            new Country {CountryNumber= "83", Title= "Bulgaria"},
            new Country {CountryNumber= "84", Title= "Hungary"},
            new Country {CountryNumber= "85", Title= "Moldova"},
            new Country {CountryNumber= "86", Title= "Italy"},
            new Country {CountryNumber= "87", Title= "Paraguay"},
            new Country {CountryNumber= "88", Title= "Honduras"},
            new Country {CountryNumber= "89", Title= "Tunisia"},
            new Country {CountryNumber= "90", Title= "Nicaragua"},
            new Country {CountryNumber= "91", Title= "Timorleste"},
            new Country {CountryNumber= "92", Title= "Bolivia"},
            new Country {CountryNumber= "93", Title= "Costarica"},
            new Country {CountryNumber= "94", Title= "Guatemala"},
            new Country {CountryNumber= "95", Title= "Uae"},
            new Country {CountryNumber= "96", Title= "Zimbabwe"},
            new Country {CountryNumber= "97", Title= "Puertorico"},
            new Country {CountryNumber= "98", Title= "Sudan"},
            new Country {CountryNumber= "99", Title= "Togo"},
            new Country {CountryNumber= "100", Title= "Kuwait"},
            new Country {CountryNumber= "101", Title= "Salvador"},
            new Country {CountryNumber= "102", Title= "Libyan"},
            new Country {CountryNumber= "103", Title= "Jamaica"},
            new Country {CountryNumber= "104", Title= "Trinidad"},
            new Country {CountryNumber= "105", Title= "Ecuador"},
            new Country {CountryNumber= "106", Title= "Swaziland"},
            new Country {CountryNumber= "107", Title= "Oman"},
            new Country {CountryNumber= "108", Title= "Bosnia"},
            new Country {CountryNumber= "109", Title= "Dominican"},
            new Country {CountryNumber= "110", Title= "Syrian"},
            new Country {CountryNumber= "111", Title= "Qatar"},
            new Country {CountryNumber= "112", Title= "Panama"},
            new Country {CountryNumber= "113", Title= "Cuba"},
            new Country {CountryNumber= "114", Title= "Mauritania"},
            new Country {CountryNumber= "115", Title= "Sierraleone"},
            new Country {CountryNumber= "116", Title= "Jordan"},
            new Country {CountryNumber= "117", Title= "Portugal"},
            new Country {CountryNumber= "118", Title= "Barbados"},
            new Country {CountryNumber= "119", Title= "Burundi"},
            new Country {CountryNumber= "120", Title= "Benin"},
            new Country {CountryNumber= "121", Title= "Brunei"},
            new Country {CountryNumber= "122", Title= "Bahamas"},
            new Country {CountryNumber= "123", Title= "Botswana"},
            new Country {CountryNumber= "124", Title= "Belize"},
            new Country {CountryNumber= "125", Title= "Caf"},
            new Country {CountryNumber= "126", Title= "Dominica"},
            new Country {CountryNumber= "127", Title= "Grenada"},
            new Country {CountryNumber= "128", Title= "Georgia"},
            new Country {CountryNumber= "129", Title= "Greece"},
            new Country {CountryNumber= "130", Title= "Guineabissau"},
            new Country {CountryNumber= "131", Title= "Guyana"},
            new Country {CountryNumber= "132", Title= "Iceland"},
            new Country {CountryNumber= "133", Title= "Comoros"},
            new Country {CountryNumber= "134", Title= "Saintkitts"},
            new Country {CountryNumber= "135", Title= "Liberia"},
            new Country {CountryNumber= "136", Title= "Lesotho"},
            new Country {CountryNumber= "137", Title= "Malawi"},
            new Country {CountryNumber= "138", Title= "Namibia"},
            new Country {CountryNumber= "139", Title= "Niger"},
            new Country {CountryNumber= "140", Title= "Rwanda"},
            new Country {CountryNumber= "141", Title= "Slovakia"},
            new Country {CountryNumber= "142", Title= "Suriname"},
            new Country {CountryNumber= "143", Title= "Tajikistan"},
            new Country {CountryNumber= "144", Title= "Monaco"},
            new Country {CountryNumber= "145", Title= "Bahrain"},
            new Country {CountryNumber= "146", Title= "Reunion"},
            new Country {CountryNumber= "147", Title= "Zambia"},
            new Country {CountryNumber= "148", Title= "Armenia"},
            new Country {CountryNumber= "149", Title= "Somalia"},
            new Country {CountryNumber= "150", Title= "Congo"},
            new Country {CountryNumber= "151", Title= "Chile"},
            new Country {CountryNumber= "152", Title= "Burkinafaso"},
            new Country {CountryNumber= "153", Title= "Lebanon"},
            new Country {CountryNumber= "154", Title= "Gabon"},
            new Country {CountryNumber= "155", Title= "Albania"},
            new Country {CountryNumber= "156", Title= "Uruguay"},
            new Country {CountryNumber= "157", Title= "Mauritius"},
            new Country {CountryNumber= "158", Title= "Bhutan"},
            new Country {CountryNumber= "159", Title= "Maldives"},
            new Country {CountryNumber= "160", Title= "Guadeloupe"},
            new Country {CountryNumber= "161", Title= "Turkmenistan"},
            new Country {CountryNumber= "162", Title= "Frenchguiana"},
            new Country {CountryNumber= "163", Title= "Finland"},
            new Country {CountryNumber= "164", Title= "Saintlucia"},
            new Country {CountryNumber= "165", Title= "Luxembourg"},
            new Country {CountryNumber= "166", Title= "Saintvincentgrenadines"},
            new Country {CountryNumber= "167", Title= "Equatorialguinea"},
            new Country {CountryNumber= "168", Title= "Djibouti"},
            new Country {CountryNumber= "169", Title= "Antiguabarbuda"},
            new Country {CountryNumber= "170", Title= "Caymanislands"},
            new Country {CountryNumber= "171", Title= "Montenegro"},
            new Country {CountryNumber= "172", Title= "Denmark"},
            new Country {CountryNumber= "173", Title= "Switzerland"},
            new Country {CountryNumber= "174", Title= "Norway"},
            new Country {CountryNumber= "175", Title= "Australia"},
            new Country {CountryNumber= "176", Title= "Eritrea"},
            new Country {CountryNumber= "177", Title= "Southsudan"},
            new Country {CountryNumber= "178", Title= "Saotomeandprincipe"},
            new Country {CountryNumber= "179", Title= "Aruba"},
            new Country {CountryNumber= "180", Title= "Montserrat"},
            new Country {CountryNumber= "181", Title= "Anguilla"},
            new Country {CountryNumber= "183", Title= "Northmacedonia"},
            new Country {CountryNumber= "184", Title= "Seychelles"},
            new Country {CountryNumber= "185", Title= "New Caledonia"},
            new Country {CountryNumber= "186", Title= "Capeverde"},
            new Country {CountryNumber= "187", Title= "United States"},
            new Country {CountryNumber= "189", Title= "Fiji"},
            new Country {CountryNumber= "196", Title= "Singapore"},
            new Country {CountryNumber= "201", Title= "Gibraltar"},
            new Country {CountryNumber= "0", Title= "Russia"},
        };
    }

    public class Country
    {
        public string CountryNumber { get; set; }
        public string Title { get; set; }
    }
}
